### ISSUE TITLE
Creating an empty schema with input processor fails

### ISSUE THREAD

**Issue by sled** [dry-rb/dry-validation#112]
When creating an empty schema with an input processor I get an exception, if I add at least one key, it works fine.

```
Dry::Validation.Schema do
    configure { config.input_processor = :json }
end
```

Results in:

```
NoMethodError: undefined method `each_with_object' for nil:NilClass
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/hash.rb:7:in `schema'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/hash.rb:23:in `symbolized'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/decorator.rb:35:in `method_missing'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/compiler.rb:79:in `merge_with'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/compiler.rb:67:in `visit_json_hash'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/compiler.rb:28:in `visit_type'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/compiler.rb:15:in `visit'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-types-0.7.1/lib/dry/types/compiler.rb:11:in `call'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-validation-0.7.4/lib/dry/validation/input_processor_compiler.rb:16:in `call'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:123:in `input_processor'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:146:in `default_options'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
	from /Users/simon/.rvm/gems/ruby-2.3.0/gems/dry-validation-0.7.4/lib/dry/validation.rb:37:in `Schema'
	from (irb):3
	from /Users/simon/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by lasseebert** [comment]
This seems like a duplicate of #101, which has been fixed in master of dry-types (here: https://github.com/dry-rb/dry-types/pull/75)

**Comment by sled** [comment]
indeed it seems like a dupe of #101, sorry :)
