### ISSUE TITLE
Guard against nil input

### ISSUE THREAD

**Issue by tak1n** [dry-rb/dry-validation#123]
Following example:

```ruby
require 'dry/validation'

schema = Dry::Validation.Schema do
  required(:token).filled(:str?)
end

result = schema.call({})
result = schema.call(nil)
```

The second `schema.call` with nil as input leads to following exception:
```
/home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicates.rb:23:in `block in <module:Predicates>': undefined method `key?' for nil:NilClass (NoMethodError)
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:13:in `apply'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:9:in `call'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/composite.rb:39:in `call'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:226:in `block in rule_results'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:225:in `each'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:225:in `each_with_object'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:225:in `rule_results'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:209:in `apply'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/bundler/gems/dry-validation-59fb0a09c499/lib/dry/validation/schema.rb:185:in `call'
        from test.rb:8:in `<main>'
```
Should we implement a nil guard on dry-v site so it throws a more user friendly exception?

Eg.: passing in nil gives the user a exception that he passed in nil to schema.call and he most likely wanted to pass in a hash.

**Comment by solnic** [comment]
You *can* do this:

``` ruby
require 'dry/validation'

schema = Dry::Validation.Schema do
  hash? do
    required(:token).filled(:str?)
  end
end

puts schema.call({}).inspect
puts schema.call(nil).inspect
```

Bad news is that error formatting is shitty:

```
#<Dry::Validation::Result output={} messages={:token=>["is missing"]}>
#<Dry::Validation::Result output=nil messages={nil=>["must be a hash"]}>
```

This is actually the same issue as #98 so I'm gonna close this one. It will be improved for 0.8.0 release.
