### ISSUE TITLE
dry-types PR 88 causes failing specs

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#151]
This PR https://github.com/dry-rb/dry-types/pull/88
Is causing a couple of the new specs to fail as they assume '' is not an array when in a form this is now not true.

I'm raising a PR as we speak.
```
Failures:

  1) Predicates: Array as macro with required with blank input is not successful
     Failure/Error: expect(result).to be_failing ['must be an array']
       expected that #<Dry::Validation::Result output={:foo=>[]} messages={}> would be failing (["must be an array"])
     # ./spec/integration/form/predicates/array_spec.rb:158:in `block (5 levels) in <top (required)>'

  2) Predicates: Array as macro with optional with blank input is not successful
     Failure/Error: expect(result).to be_failing ['must be an array']
       expected that #<Dry::Validation::Result output={:foo=>[]} messages={}> would be failing (["must be an array"])
     # ./spec/integration/form/predicates/array_spec.rb:206:in `block (5 levels) in <top (required)>'

  3) Predicates: Array with required with blank input is not successful
     Failure/Error: expect(result).to be_failing ['must be an array']
       expected that #<Dry::Validation::Result output={:foo=>[]} messages={}> would be failing (["must be an array"])
     # ./spec/integration/form/predicates/array_spec.rb:37:in `block (4 levels) in <top (required)>'
```

**Comment by timriley** [comment]
Fixed by #152
