### ISSUE TITLE
Custom Predicates errors

### ISSUE THREAD

**Issue by alex-lairan** [dry-rb/dry-validation#186]
Hi here,

When I try to create custom predicates, I got somes errors. 
This is my test:
```ruby
require 'dry-validation'
require 'pp'

schema = Dry::Validation.Schema do
  configure do
    config.messages_file = './errors.yml'
    def valid_role?(value)
      %w(Admin Viewer Actor).include?(value)
    end
  end

  optional(:roles).each do
    schema do
      key(:name) { filled? & str? & valid_role? }
    end
  end
end

pp schema.call(roles: [{name: 'Admin'}, {name: 'Test'}]).messages
```

And the error message:
```
/home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:195:in `[]': +valid_role?+ is not a valid predicate name (ArgumentError)
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:54:in `visit_predicate'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:32:in `visit_key'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:59:in `visit_and'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:59:in `visit_and'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:254:in `block in initialize_rules'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `each'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `each_with_object'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `initialize_rules'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:174:in `initialize'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema_compiler.rb:33:in `visit_schema'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:59:in `visit_and'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:13:in `block in call'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:13:in `map'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:13:in `call'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:45:in `visit_set'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:49:in `visit_each'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:59:in `visit_and'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:32:in `visit_key'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:74:in `visit_implication'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:254:in `block in initialize_rules'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `each'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `each_with_object'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:253:in `initialize_rules'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:174:in `initialize'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
	from /home/lairan/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.7.4/lib/dry/validation.rb:37:in `Schema'
	from tests.rb:3:in `<main>'
```

Thank for your help ! :)

**Comment by alex-lairan** [comment]
With another test (same error)

```ruby
require 'dry-validation'
require 'pp'

module RolesPedicates
  include Dry::Logic::Predicates

  def valid_role?(value)
    %w(Admin Viewer Actor).include?(value)
  end
end


schema = Dry::Validation.Schema do
  configure do
    config.messages_file = './errors.yml'
    config.predicates = RolesPedicates
  end

  optional(:roles).each do
    schema do
      key(:name) { filled? & str? & valid_role? }
    end
  end
end

pp schema.call(roles: [{name: 'Admin'}, {name: 'Test'}]).messages
```
