### ISSUE TITLE
Can't use each with JSON or Form schema

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-validation#188]
```
# Works
AnswerSchema = Dry::Validation.Schema do
  each do
    schema do
      required(:option_id).filled(:int?)
    end
  end
end

p AnswerSchema.call([{option_id: 1}]).messages

# Does not work
AnswerJSON = Dry::Validation.JSON do
  each do
    schema do
      required(:option_id).filled(:int?)
    end
  end
end

/usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:80:in `merge': no implicit conversion of Dry::Types::Safe into Hash (TypeError)
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:80:in `each'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:80:in `reduce'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:80:in `merge_with'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:67:in `visit_json_hash'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:28:in `visit_type'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:15:in `visit'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-types-861c0b2619a2/lib/dry/types/compiler.rb:11:in `call'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation/input_processor_compiler.rb:16:in `call'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation/schema.rb:137:in `input_processor'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation/schema.rb:164:in `default_options'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation/schema.rb:62:in `new'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation.rb:41:in `Schema'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-46ece47c7ad1/lib/dry/validation.rb:50:in `JSON'
```

**Comment by solnic** [comment]
This is fixed via explicit type specs, so please switch to this syntax when upgrading to 0.8.0:

``` ruby
AnswerJSON = Dry::Validation.JSON do
  each do
    schema do
      required(:option_id, :int).filled(:int?)
    end
  end
end
```
