### ISSUE TITLE
Option got nil in nested schema

### ISSUE THREAD

**Issue by jandudulski** [dry-rb/dry-validation#202]
Sounds similar to #200 

Here is my spec:

```ruby
RSpec.describe Dry::Validation do
  describe "simple schema" do
    let(:schema) do
      Dry::Validation.Schema do
        configure do
          config.messages_file = "#{PROJECT_ROOT}/config/dry-errors.yml"
          option :my_id

          def eql_my_id?(value)
            my_id == value
          end
        end

        required("id").filled(:eql_my_id?)
      end
    end
    let(:params) do
      { "id" => 1 }
    end
    subject(:result) { schema.with(my_id: 1).call(params) }

    it { expect(result.success?).to be(true) }
    it { expect(result.output).to eq("id" => 1) }
    it { expect(result.messages).to eq({}) }
  end

  describe "nested schema" do
    let(:schema) do
      Dry::Validation.Schema do
        configure do
          config.messages_file = "#{PROJECT_ROOT}/config/dry-errors.yml"
          option :my_id

          def eql_my_id?(value)
            puts "my_id = #{my_id.inspect}"
            my_id == value
          end
        end

        required("data").schema do
          required("id").filled(:eql_my_id?)
        end
      end
    end
    let(:params) do
      { "data" => { "id" => 1 } }
    end
    subject(:result) { schema.with(my_id: 1).call(params) }

    it { expect(result.success?).to be(true) }
    it { expect(result.output).to eq("data" => { "id" => 1 }) }
    it { expect(result.messages).to eq({}) }
  end
end
```

And result:

```
Dry::Validation
  nested schema
my_id = nil
my_id = nil
    should eq {} (FAILED - 1)
my_id = nil
my_id = nil
    should equal true (FAILED - 2)
my_id = nil
my_id = nil
    should eq {"data"=>{"id"=>1}}
  simple schema
    should eq {"id"=>1}
    should equal true
    should eq {}

Failures:

  1) Dry::Validation nested schema should eq {}
     Failure/Error: it { expect(result.messages).to eq({}) }
     
       expected: {}
            got: {"data"=>{"id"=>["Id doesn't match"]}}
     
       (compared using ==)
     
       Diff:
       @@ -1 +1,2 @@
       +"data" => {"id"=>["Id doesn't match"]},
       
     # ./spec/api/use_cases/example_spec.rb:56:in `block (3 levels) in <top (required)>'

  2) Dry::Validation nested schema should equal true
     Failure/Error: it { expect(result.success?).to be(true) }
     
       expected true
            got false
     # ./spec/api/use_cases/example_spec.rb:54:in `block (3 levels) in <top (required)>'
```

**Comment by solnic** [comment]
This is because we don't pass options to nested schemas I believe. I'll look into that.
