### ISSUE TITLE
support enum as type in array validation

### ISSUE THREAD

**Issue by andreaseger** [dry-rb/dry-validation#211]
enum type from dry-types are quite useful but I ran into an issue when using them to validate the elements of an array.

Have a look at this example

```
#!/usr/bin/env ruby
require "bundler/inline"

gemfile true do
  source "https://rubygems.org"
  gem "dry-validation", "~> 0.9"
end

module Types
  include Dry::Types.module
  Gender = Types::Strict::String.enum("male", "female")
  SportTypes = Types::Strict::String.enum("running", "hicking")
end

schema = Dry::Validation.Form do
  required(:gender).filled(Types::Gender)
  required(:sport_types).each(Types::SportTypes)
end

p schema.call({"gender" => "male", "sport_types" => ["running"]}).success?
p schema.call({"gender" => "female", "sport_types" => ["hicking"]}).success?
p schema.call({"gender" => "male", "sport_types" => ["running","duck"]}).success?

__END__
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using concurrent-ruby 1.0.2
Using dry-equalizer 0.2.0
Using dry-monads 0.0.2
Using ice_nine 0.11.2
Using inflecto 0.0.2
Using bundler 1.12.5
Using dry-configurable 0.1.6
Using dry-container 0.3.4
Using dry-logic 0.3.0
Using dry-types 0.8.0
Using dry-validation 0.9.1
/home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/value.rb:179:in `block in infer_predicates': #<Dry::Types::Enum type=#<Dry::Types::Constrained type=#<Dry::Types::Definition primitive=String options={}> options={:rule=>#<Dry::Logic::Rule::Conjunction left=#<Dry::Logic::Rule::Value predicate=#<Dry::Logic::Predicate::Curried id=:type? args=[String]> options={}> right=#<Dry::Logic::Rule::Value predicate=#<Dry::Logic::Predicate::Curried id=:included_in? args=[["running", "hicking"]]> options={}>>} rule=#<Dry::Logic::Rule::Conjunction left=#<Dry::Logic::Rule::Value predicate=#<Dry::Logic::Predicate::Curried id=:type? args=[String]> options={}> right=#<Dry::Logic::Rule::Value predicate=#<Dry::Logic::Predicate::Curried id=:included_in? args=[["running", "hicking"]]> options={}>>> options={:values=>["running", "hicking"]} values=["running", "hicking"]> is not a symbol nor a string (TypeError)
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/value.rb:173:in `map'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/value.rb:173:in `infer_predicates'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/value.rb:53:in `each'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/rule.rb:104:in `each'
        from dry-test.rb:17:in `block in <main>'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/class_interface.rb:46:in `instance_exec'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation/schema/class_interface.rb:46:in `define'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation.rb:39:in `Schema'
        from /home/ane/.rbenv/versions/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.1/lib/dry/validation.rb:49:in `Form'
        from dry-test.rb:15:in `<main>'
```

After poking around in the code and some older issues I saw that the enum type has a rule and could create an ast from that as @solnic here https://github.com/dry-rb/dry-validation/pull/86#issuecomment-202784291
Any plans on fixing that in the - arguably hacky -way mentioned or in a proper way to support enum types for array elements in validation?

**Comment by solnic** [comment]
It's now fixed in 0.9.2, thanks for reporting
