### ISSUE TITLE
Dry-Validation cannot used custom types from Dry-Types

### ISSUE THREAD

**Issue by kirs** [dry-rb/dry-validation#218]
``` ruby
require 'dry-validation'
require 'money' # gem money

class MoneyParser
  def self.constructor(input)
    input.to_money
  end
end

Dry::Types.register(
  'custom_money_type',
  Dry::Types::Definition.new(Money).constructor(MoneyParser.method(:constructor))
)

DryMoney = Dry::Types['custom_money_type']
puts DryMoney['2.2'].inspect
# works so far
# => #<Money value:2.20>

schema = Dry::Validation.Form do
  required(:amount).filled(DryMoney)
end
schema.call({amount: "1.1"})
```

Stacktrace:

```
/Users/kir/Projects/shopify/vendor/bundle/gems/dry-types-0.8.1/lib/dry/types/constructor.rb:69:in `method_missing': undefined method `to_ast' for #<Dry::Types::Constructor:0x007fa52a2c14c0> (NoMethodError)
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/value.rb:162:in `node'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/rule.rb:187:in `key'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/rule.rb:167:in `block in infer_predicates'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/rule.rb:161:in `map'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/rule.rb:161:in `infer_predicates'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/rule.rb:65:in `filled'
        from repro.rb:20:in `block in <main>'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/class_interface.rb:46:in `instance_exec'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/class_interface.rb:46:in `define'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation.rb:39:in `Schema'
        from /Users/kir/Projects/shopify/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation.rb:49:in `Form'
        from repro.rb:19:in `<main>'
```

cc @solnic

**Comment by solnic** [comment]
Only constrained types are supported as predicates in macros like `filled` etc. but for input-parsing you can enable type_specs and do this:

``` ruby
require 'dry-validation'
require 'money' # gem money

module Types
  include Dry::Types.module

  Money = Dry::Types::Definition
    .new(Money)
    .constructor { |input| ::Money.new(input) } # simplified, you gotta handle errors here
end

puts Types::Money['2.2'].inspect
#<Money fractional:2 currency:USD>

schema = Dry::Validation.Form do
  configure do
    config.type_specs = true

    def usd?(m)
      m.currency == 'USD'
    end
  end

  required(:amount, Types::Money).filled(:usd?)
end

puts schema.call(amount: "1.1").inspect
#<Dry::Validation::Result output={:amount=>#<Money fractional:1 currency:USD>} messages={}>
```

In general the idea is that your custom type **tries** to parse the input, if it can't convert then raise `TypeError`. If you don't want to raise, you can return original input and add a predicate for type checking so ie: `required(:amount, Types::Money).value(type: Money, :usd?)`.

**Comment by kirs** [comment]
Thank you for the tip!
I tried `type_specs` and looks like it changes the schema behaviour in some way:

```ruby
require 'bundler/setup'
require 'money'
require 'dry-validation'

module Types
  include Dry::Types.module

  Money = Dry::Types::Definition
    .new(Money)
    .constructor { |input| ::Money.new(input) }
end

Schema = Dry::Validation.Form do
  optional(:order_id).maybe(:int?)
  optional(:name).maybe(:str?)
  optional(:amount).maybe(:float?)
end

TypeSpecsSchema = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  optional(:order_id).maybe(:int?)
  optional(:name).maybe(:str?)
  optional(:amount, Types::Money)
end

input = { order_id: 1, amount: 4.5, name: "kir", unknown: "should be filtered out" }
puts Schema.call(input).output.inspect
# => {:order_id=>1, :name=>"kir", :amount=>4.5}
# as expected

puts TypeSpecsSchema.call(input).output.inspect
# => {:amount=>#<Money value:4.50>}
# why the rest of fields are missing?
```

**Comment by solnic** [comment]
@kirs aah yeah that's a nasty gotcha, basically keys w/o type will be skipped by the input pre-processing function, if you specify types for `:order_id` and `:amount` you'll get back the whole hash. I should either add raising arg-error when type is missing, or just default to a pass-through type. Not sure which would be better.

**Comment by kirs** [comment]
Got it.

`optional(:order_id, :int)` works fine but when I tried `optional(:name, :str)` it raised:

```
/project/vendor/bundle/gems/dry-container-0.3.4/lib/dry/container/resolver.rb:22:in `block in call': Nothing registered with the
 key "str" (Dry::Container::Error)
        from /project/vendor/bundle/gems/dry-container-0.3.4/lib/dry/container/resolver.rb:21:in `fetch'
        from /project/vendor/bundle/gems/dry-container-0.3.4/lib/dry/container/resolver.rb:21:in `call'
        from /project/vendor/bundle/gems/dry-container-0.3.4/lib/dry/container/mixin.rb:105:in `resolve'
        from /project/vendor/bundle/gems/dry-container-0.3.4/lib/dry/container/mixin.rb:118:in `[]'
        from /project/vendor/bundle/gems/dry-types-0.8.1/lib/dry/types.rb:67:in `block in []'
        from /project/vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:133:in `block in fetch_or_store'
        from /project/vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:122:in `fetch'
        from /project/vendor/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:132:in `fetch_or_store'
        from /project/vendor/bundle/gems/dry-types-0.8.1/lib/dry/types.rb:58:in `[]'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:66:in `lookup_type'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:45:in `resolve_spec'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:18:in `block in build_type_map'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:17:in `each'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:17:in `reduce'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/type_specs.rb:17:in `build_type_map'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/class_interface.rb:60:in `block in defin
e'
        from /project/vendor/bundle/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:65:in `configure'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation/schema/class_interface.rb:56:in `define'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation.rb:39:in `Schema'
        from /project/vendor/bundle/gems/dry-validation-0.9.2/lib/dry/validation.rb:49:in `Form'

```

I replaced it with `optional(:name, Dry::Types['coercible.string'])` and it works.

Is it the expected behaviour?

Thanks!

**Comment by solnic** [comment]
Ooops. It is a bug. I'll improve this somehow.

**Comment by kirs** [comment]
I think we should also educate people to show what's the difference between:

```
optional(:age, :int)
optional(:age, :int).maybe
optional(:age).maybe(:int?)
```

**Comment by solnic** [comment]
We might come up with a bunch of schema types where the type would indicate how a schema object behaves. We'll see :)

**Comment by contentfree** [comment]
Can a list of the built-in shorthand types, such as `:int` and `:string`, be published somewhere? The only mention in the docs, currently, is the sentence 

> Luckily, dry-validation comes with the usual suspects pre-built, so you don’t have to type Types::String long-hand.

**Comment by kaikuchn** [comment]
This does not seem to work in conjunction with arrays?
To reuse the money example, say you have a money tuple for gross and net amounts:

```ruby
schema = Dry::Validation.Form do
  configure do
    config.type_specs = true

    def money_tuple?(gross, net)
      gross > net
    end
  end

  required(:gross_and_net, [Types::Money]) { array? & money_tuple? }
end
```

The actual predicate is not of interest (not sure if my `money_tuple?` example could work). The problem I'm facing is that I get this error:

```ruby
Dry::Container::Error: Nothing registered with the key "#"
```

**Comment by solnic** [comment]
@kaikuchn You want `Types::Strict::Array.member(Types::Money)`

**Comment by kaikuchn** [comment]
Yes, that works! Thank you for pointing me in the right direction!
I had assumed that `[Type]` would be equivalent to this.

**Comment by solnic** [comment]
@kaikuchn passing an array with types or symbol identifiers is used for sum types, ie `[:nil, :int]` is the same as `Types::Strict::Nil | Types::Form::Int]` (in form schemas). We should raise a meaningful error if somebody passed an array with a single element though.

**Comment by kaikuchn** [comment]
Ah okay, the I misunderstood the comment about member types in [this (not linked since it's just an extraction from a blog post) doc about](http://dry-rb.org/gems/dry-validation/type-specs/).

Thanks again for clarifying. Btw. I really like the result of introducing dry-validations into my app, so thanks for this awesome gem! :)

**Comment by flash-gordon** [comment]
As far as I can see no issues left here. BTW you may have heard we're working on the next release and it'll be awesome ;)
