### ISSUE TITLE
each and included_in? fail together

### ISSUE THREAD

**Issue by Goltergaul** [dry-rb/dry-validation#246]
Hi,

i've got this rule `optional(:roles).filled { each(included_in?(["admin", "manager"])) & max_size?(2) }`
(I want to check that every array value is either "admin" or "manager".)

When I validate the following hash against it it fails with the following error:

```
{
"roles": ["foo"]
}
```

```
NoMethodError: undefined method `to_ary' for #<Dry::Validation::Schema::Rule:0x005589a493ce88>
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/rule.rb:182:in `method_missing'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/value.rb:175:in `Array'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/value.rb:175:in `each'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/value.rb:175:in `flat_map'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/value.rb:175:in `infer_predicates'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/value.rb:53:in `each'
  /home/dog/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-validation-0.9.5/lib/dry/validation/schema/key.rb:26:in `each'
```

Is this a bug or did I use the wrong syntax?

**Comment by solnic** [comment]
This should work:

``` ruby
Dry::Validation.Schema do
  optional(:roles).value(type?: Array, max_size?: 2) { each(included_in?: %w(admin manager)) }
end
```

You could also add a custom predicate to get rid of `each` (and it will be faster), ie:

``` ruby
Dry::Validation.Schema do
  configure do
    def self.messages
      super.merge(en: { errors: { one_of?: 'must be one of: %{values}'}})
    end

    def one_of?(values, arr)
      arr.all? { |value| values.include?(value) }
    end
  end

  optional(:roles).value(type?: Array, max_size?: 2, one_of?: %w(admin manager))
end
```

@fran-worley we should add such predicate to dry-logic I think, it's a very common thing to do

**Comment by Goltergaul** [comment]
@solnic thank you very much, that is working :)
