### ISSUE TITLE
Error when requiring dry-validation

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-validation#256]
Gemfile:
```
source 'https://rubygems.org'
gem 'dry-validation'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    concurrent-ruby (1.0.2)
    dry-configurable (0.1.7)
      concurrent-ruby (~> 1.0)
    dry-container (0.5.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.1.0)
      concurrent-ruby (~> 1.0)
    dry-equalizer (0.2.0)
    dry-logic (0.4.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-core (~> 0.1)
      dry-equalizer (~> 0.2)
    dry-monads (0.2.0)
      dry-equalizer
    dry-types (0.8.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-monads (>= 0.0.1)
      ice_nine (~> 0.11)
      inflecto (~> 0.0.0, >= 0.0.2)
    dry-validation (0.9.5)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-container (~> 0.2, >= 0.2.8)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-types (~> 0.8, >= 0.8.1)
    ice_nine (0.11.2)
    inflecto (0.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  dry-validation

BUNDLED WITH
   1.12.5
```

Code:
```
require 'dry-validation'
```

Error:
```
/home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `curry': no implicit conversion of Class into Integer (TypeError)
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `block in Rule'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `each'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `map'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `Rule'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/builder.rb:22:in `constrained'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/core.rb:32:in `block in <module:Types>'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/core.rb:31:in `each'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/core.rb:31:in `<module:Types>'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/core.rb:2:in `<module:Dry>'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types/core.rb:1:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.8.1/lib/dry/types.rb:104:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-validation-0.9.5/lib/dry/validation/input_processor_compiler.rb:1:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-validation-0.9.5/lib/dry/validation/schema/deprecated.rb:1:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-validation-0.9.5/lib/dry/validation/schema.rb:16:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-validation-0.9.5/lib/dry/validation.rb:5:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/monkey/.gem/ruby/2.2.5/gems/dry-validation-0.9.5/lib/dry-validation.rb:1:in `<top (required)>'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/rubies/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from t.rb:1:in `<main>'
```

**Comment by solnic** [comment]
This is fixed now as 0.10.0 has been released.
