### ISSUE TITLE
Can't use each { schema FormSchema }

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-validation#258]
```
require 'dry-validation'

Schema = Dry::Validation.Schema do
end

# This works fine!
SchemaContainer = Dry::Validation.Schema do
  each { schema Schema }
end

Form = Dry::Validation.Form do
end

# This fails :(
FormContainer = Dry::Validation.Form do
  each { schema Form }
end
```

```
/home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:80:in `merge': no implicit conversion of Dry::Types::Safe into Hash (TypeError)
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:80:in `each'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:80:in `reduce'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:80:in `merge_with'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:58:in `visit_form_hash'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:28:in `visit_type'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:15:in `visit'
    from /home/monkey/.gem/ruby/2.2.5/gems/dry-types-0.9.0/lib/dry/types/compiler.rb:11:in `call'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation/input_processor_compiler.rb:16:in `call'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation/schema/class_interface.rb:163:in `default_options'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation/schema/class_interface.rb:34:in `new'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation.rb:28:in `Schema'
    from /home/monkey/.gem/ruby/2.2.5/bundler/gems/dry-validation-54d073ba1e54/lib/dry/validation.rb:34:in `Form'
    from t2.rb:16:in `<main>'
```

**Comment by solnic** [comment]
Could you try`each(Schema)`?

**Comment by joevandyk** [comment]
doesn't work

**Comment by solnic** [comment]
If you switch to explicit type specs it'll work. This is one of the reasons why implicit coercions will be removed in 1.0.0. Could you try that? It goes like this:

``` ruby
FormContainer = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  each { schema Form }
end
```

**Comment by joevandyk** [comment]
I can try... this seems pretty confusing though :)

**Comment by solnic** [comment]
Which part is confusing?

**Comment by joevandyk** [comment]
My immediate questions: what is `config.type_spec`, what does it mean to
set it to true, and why is it related to this problem?

**Comment by solnic** [comment]
@joevandyk http://dry-rb.org/gems/dry-validation/type-specs/ I hope this explains it

**Comment by joevandyk** [comment]
Setting type specs to true didn't seem to fix it. 

Is that documentation linked from anywhere? Didn't see it on the menu.

**Comment by solnic** [comment]
I'll address this in 0.10.4

> Is that documentation linked from anywhere? Didn't see it on the menu.

it's not, I need to re-work this section as it was cut/paste from a blog post 😅

**Comment by i2chris** [comment]
@joevandyk Did you manage to fix this?

**Comment by flash-gordon** [comment]
This doesn't raise an error in dry-schema but I stumbled upon another issue, see https://github.com/dry-rb/dry-schema/issues/25. I'm closing this one, we'll solve the dry-schema's issue before the next release.
