### ISSUE TITLE
Bug in message compiling when validating array of multiple schemas

### ISSUE THREAD

**Issue by arobecke** [dry-rb/dry-validation#280]
I think there is a bug when compiling *Or* messages

Let's say we have the following schema defined:

```
type_a = Dry::Validation.Schema do
  required(:type).filled(format?: /\AA\z/)
end

type_b = Dry::Validation.Schema do
  required(:type).filled(format?: /\AB\z/)
end

schema = Dry::Validation.Schema do
  required(:data).each { schema(type_a) | schema(type_b) }
end

input = {
  data: [
    { type: 'A' },
    { type: 'B' }
  ]
}


schema.call(input).success? # => true
```

As long as the input matches the schema no problem. But when the input does not match the schema and I try to compile errors an *Or* error message is instantiated with an array as left param and then path is called on the array instead of the left item.  

```
input = {
  data: [
    { type: 'A' },
    { type: 'B' },
    { type: 'BANG!' }
  ]
}


schema.call(input).success? # => false
schema.call(input).errors

NoMethodError: undefined method `path' for #<Array:0x000000027c4168>
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message.rb:24:in `initialize'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:94:in `new'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:94:in `visit_or'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:137:in `visit_key'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:141:in `block in visit_set'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:141:in `map'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:141:in `visit_set'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:48:in `visit_failure'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:137:in `visit_key'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:48:in `visit_failure'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `block in call'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `map'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `call'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/result.rb:54:in `message_set'
        from /home/andy/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.10.3/lib/dry/validation/result.rb:46:in `errors'
        from (irb):132
```

**Comment by backus** [comment]
I've run into this bug too. I think it is simpler than what @arobecke has described. Here is a simpler reproduction:

```ruby
> (Dry::Validation.Schema { required(:foo) {  str? & filled? | int? } }).call({}).messages
NoMethodError: undefined method `path' for #<Array:0x007ff08139a930>
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message.rb:24:in `initialize'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:94:in `new'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:94:in `visit_or'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:53:in `visit_hint'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:81:in `block in visit_and'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:81:in `map'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:81:in `visit_and'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:48:in `visit_failure'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:43:in `visit'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `block in call'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `map'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message_compiler.rb:39:in `call'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/result.rb:54:in `message_set'
... 2 levels...
	from /Users/johnbackus/.rubies/ruby-2.3.3/bin/irb:11:in `<top (required)>'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /Users/johnbackus/.gem/ruby/2.3.3/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /Users/johnbackus/.gem/ruby/2.3.3/bin/bundle:22:in `load'
	from /Users/johnbackus/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'
```

**Comment by backus** [comment]
Digging a bit deeper, it looks like the issue is caused by `Message::Or` expecting to always receive a `Hint` but actually receiving `Array<Hint>` in cases where the left hand side of the validation is many predicates chained together:

```ruby
irb(main):003:0> (Dry::Validation.Schema { required(:foo) {  str? & filled? | int? } }).call({}).messages

From: /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message.rb @ line 25 Dry::Validation::Message::Or#initialize:

    20: def initialize(left, right, messages)
    21:   @left = left
    22:   @right = right
    23:   @messages = messages
    24:   require 'pry'; require 'pry-byebug'; binding.pry
 => 25:   @path = left.path
    26: end

1 (#<Dry::Validation::Message::Or>) p left
[#<Dry::Validation::Hint predicate=:str? path=[:foo] text="must be a string" options={:args=>[], :input=>nil, :rule=>:foo, :check=>nil}>, #<Dry::Validation::Hint predicate=:filled? path=[:foo] text="must be filled" options={:args=>[], :input=>nil, :rule=>:foo, :check=>nil}>]
2 (#<Dry::Validation::Message::Or>)
NoMethodError: undefined method `path' for #<Array:0x007ffa07229cd8>
  ...
```

```ruby
irb(main):004:0> (Dry::Validation.Schema { required(:foo) {  str? | int? } }).call({}).messages

From: /Users/johnbackus/.gem/ruby/2.3.3/gems/dry-validation-0.10.3/lib/dry/validation/message.rb @ line 25 Dry::Validation::Message::Or#initialize:

    20: def initialize(left, right, messages)
    21:   @left = left
    22:   @right = right
    23:   @messages = messages
    24:   require 'pry'; require 'pry-byebug'; binding.pry
 => 25:   @path = left.path
    26: end

1 (#<Dry::Validation::Message::Or>) p left
#<Dry::Validation::Hint predicate=:str? path=[:foo] text="must be a string" options={:args=>[], :input=>nil, :rule=>:foo, :check=>nil}>
=> #<Dry::Validation::Hint predicate=:str? path=[:foo] text="must be a string" options={:args=>[], :input=>nil, :rule=>:foo, :check=>nil}>
2 (#<Dry::Validation::Message::Or>)
=> {:foo=>["is missing", "must be a string or must be an integer"]}
```

**Comment by arobecke** [comment]
It's exactly like @backus says. I guess my description of the problem was just silly imprecise.

**Comment by solnic** [comment]
I'll try to fix it in 0.10.x

**Comment by dw33n** [comment]
Has this been fixed yet? I'm occasionally getting this this message. `required(:paramname).filled { (str? & format?(regex)) | int? }`

It breaks hitting the int? when I remove the | int? it works. Still I would like for the | int? to be there as there are occiasions when the param isn't a string  but an int.

**Comment by luka-n** [comment]
Still an issue with 0.11.1. Would this be a difficult bug to fix?

**Comment by flash-gordon** [comment]
This is still an issue for dry-schema, I opened an issue, track it for progress https://github.com/dry-rb/dry-schema/issues/26
