### ISSUE TITLE
TypeError when trying to access messages on result

### ISSUE THREAD

**Issue by jmrepetti** [dry-rb/dry-validation#356]
Hello, I'm trying to access the messages on the result and it fail when I define the schema using the block syntax for a required filled attribute. 

I'm using **ruby 2.4.1p111** On **OSX Darwin 16.7.0 Darwin Kernel Version 16.7.0**

I didn't have much time to debug it. Below there's and example of the problem, the schemas are a bit different. On the failing one, I use a logic predicate to allow int or string. 

It's me the problem?

Working schema:

```ruby
work = Dry::Validation.Schema do
  required(:nested_schema).schema do
    required(:code).filled(:str?)
  end
end

work.({}).messages
=> {:nested_schema=>["is missing"]}
```

Failing schema:

```ruby
doesnt_work = Dry::Validation.Schema do
  required(:nested_schema).schema do
    required(:code).filled { str? | int? }
  end
end      

doesnt_work.({}).messages
TypeError: no implicit conversion of Symbol into Integer
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:113:in `[]'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:113:in `block in initialize_placeholders!'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:106:in `each'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:106:in `reduce'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:106:in `initialize_placeholders!'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:27:in `initialize'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:16:in `new'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_set.rb:16:in `[]'
	from ($HOME)/Development/dry-validation/lib/dry/validation/message_compiler.rb:36:in `call'
	from ($HOME)/Development/dry-validation/lib/dry/validation/result.rb:53:in `message_set'
	from ($HOME)/Development/dry-validation/lib/dry/validation/result.rb:41:in `messages'
	from (irb):6
```

**node** variable inside the while block result in empty array and it fail when trying to do **node[key]**

```ruby
#file dry-validation/lib/dry/validation/message_set.r:105
      def initialize_placeholders!
        @placeholders = paths.reduce({}) do |hash, path|
          curr_idx = 0
          last_idx = path.size - 1
          node = hash

          while curr_idx <= last_idx do
            key = path[curr_idx]
            node = (node[key] || node[key] = curr_idx < last_idx ? {} : [])
            curr_idx += 1
          end

          hash
        end
      end
```

So far I've found that **paths** variable for the working schema is:

```ruby
paths => [[:nested_schema]]
````
and for the failing schema is

```ruby
paths => [[:nested_schema], [:nested_schema, :code]]
```

I'm going to keep searching for a solution later, for now I'll change the schema definition to avoid the exception.

Awesome library!

**Comment by bolshakov** [comment]
I have the same problem with the following schema:

```ruby
schema = Dry::Validation.Schema do
  required(:attributes).schema do
    optional(:text) { int? | none? }
  end
end

schema.({}).messages
TypeError: no implicit conversion of Symbol into Integer
```

But in my case, it's possible to rewrite it as:

```ruby
schema = Dry::Validation.Schema do
  required(:attributes).schema do
    optional(:text).maybe(:int?)
  end
end
```

**Comment by flash-gordon** [comment]
Posted it to https://github.com/dry-rb/dry-schema/issues/26

**Comment by jaswinder97** [comment]
@flash-gordon how did you resolve it? should I use latest version?

**Comment by flash-gordon** [comment]
@jaswinder97 yes you should
