### ISSUE TITLE
Nothing registreded with the key '#' when defining schema for array of user-defined values

### ISSUE THREAD

**Issue by apohllo** [dry-rb/dry-validation#379]
I am trying to use type_specs with form validation and and array of values of user-defined type:

```ruby
require 'dry-validation'
require 'dry-types'

module Types
  include Dry::Types.module
  MyType = Types::String.constructor do |value|
    value ? value.upcase : value
  end

  MyTypeArray = Dry::Types['form.array'].of(MyType)
end

MySchema = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  # This causes an exception: 
  #required(:element, [Types::MyType]).filled
  required(:element, Types::MyTypeArray).filled
end

MySchema.call({element: %w{a b c} })
```
The only way it works is with the MyTypeArray. The first version (with more convenient syntaxt) does not work - it raises the following exception:

```
/home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-container-0.6.0/lib/dry/container/resolver.rb:22:in `block in call': Nothing registered with the key "#" (Dry::Container::Error)
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-container-0.6.0/lib/dry/container/resolver.rb:21:in `fetch'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-container-0.6.0/lib/dry/container/resolver.rb:21:in `call'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-container-0.6.0/lib/dry/container/mixin.rb:112:in `resolve'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-container-0.6.0/lib/dry/container/mixin.rb:125:in `[]'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-types-0.12.2/lib/dry/types.rb:89:in `block in []'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:133:in `block in fetch_or_store'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:132:in `fetch_or_store'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-types-0.12.2/lib/dry/types.rb:82:in `[]'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:66:in `lookup_type'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:53:in `resolve_spec'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:18:in `block in build_type_map'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:17:in `each'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:17:in `reduce'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/type_specs.rb:17:in `build_type_map'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:64:in `block in define'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:70:in `configure'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/form.rb:14:in `configure'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:60:in `define'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation.rb:18:in `Schema'
	from /home/apohllo/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.11.1/lib/dry/validation.rb:29:in `Form'
	from work/dry-validation-issue.rb:11:in `<main>'
```

I am not sure if the `[MyType]` syntax is valid, but I extrapolated it from `[:int]`, which I found in the `dry-validation` tests.

**Comment by flash-gordon** [comment]
`Dry::Types['form.array'].of(MyType)` is the correct form, arrays like `[:nil, :integer]` are used for sum types, it's not what you're after here.
BTW, in the next version array types can be specified with a shortcut

```ruby
MySchema = Dry::Schema.Form do
  required(:element).filled(array[Types::MyType])
end
```

**Comment by apohllo** [comment]
Thanks for the explanation. Any ideas when the next version will be released?

**Comment by flash-gordon** [comment]
I'm not in power to give any specific dates, please track the progress in https://github.com/dry-rb/dry-validation/pull/440 We're moving at a decent pace atm
