### ISSUE TITLE
Undefined method visit_d for an "optional" validation

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#386]
_From @chikamichi on December 15, 2016 11:5_

Hi,

Using dry-types 0.9.3 through dry-validation, this simple rule:

``` ruby
optional('draft').maybe(:str?)
```

triggers:

```
/var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:15:in `visit': undefined method `visit_d' for #<Dry::Types::Compiler:0x000000055df778 @registry=Dry:
:Types> (NoMethodError)
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:35:in `block in visit_sum'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:35:in `map'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:35:in `visit_sum'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:15:in `visit'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:80:in `block in merge_with'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:80:in `map'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:80:in `merge_with'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:52:in `visit_hash'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:28:in `visit_type'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:15:in `visit'
        from /var/lib/gems/2.2.0/gems/dry-types-0.9.3/lib/dry/types/compiler.rb:11:in `call'
        from /var/lib/gems/2.2.0/gems/dry-validation-0.10.4/lib/dry/validation/input_processor_compiler.rb:16:in `call'
        from /var/lib/gems/2.2.0/gems/dry-validation-0.10.4/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
        from /var/lib/gems/2.2.0/gems/dry-validation-0.10.4/lib/dry/validation/schema/class_interface.rb:163:in `default_options'
        from /var/lib/gems/2.2.0/gems/dry-validation-0.10.4/lib/dry/validation/schema/class_interface.rb:34:in `new'
        from /var/lib/gems/2.2.0/gems/dry-validation-0.10.4/lib/dry/validation.rb:26:in `Schema'
```

Nothing fancy about the way I use dry-validation here. `required` works just fine, the error only gets triggered by `optional` *with a block*, therefore I suspect either `visit_sum` to be doing something wrong, or what's fed to `visit_sum` to be incorrect.

_Copied from original issue: dry-rb/dry-types#172_

**Comment by solnic** [comment]
_From @chikamichi on December 16, 2016 12:24_

I've found that the error only occurs when activating dry-validation's sanitizer (`config.input_processor = :sanitizer`). Let me know if you'd like me to report the bug on the dry-validation issue tracker instead.

**Comment by solnic** [comment]
_From @flash-gordon on February 1, 2018 23:17_

I'll close this issue since it's on the dry-v side mostly. We are working on dry-validation 1.0, it's going to take a while but we hope to push a beta in two to three months (optimistic mode on). It's probably a good idea to check if this will work fine there so pls bring this issue to dry-validation's repo.

**Comment by mtomov** [comment]
Can confirm the issue. Thanks!
