### ISSUE TITLE
wrong number of arguments (0 for -1) (ArgumentError)

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-validation#421]
Steps to reproduce:

```
git clone https://github.com/mensfeld/dry-problem
cd dry-problem
./run.sh
```

The second example (despite correct ruby syntax) fails.

```
Traceback (most recent call last):
  26: from break.rb:21:in `<main>'
  25: from dry-validation-0.12.1/lib/dry/validation/schema.rb:72:in `call'
  24: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `call'
  23: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `reduce'
  22: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `each'
  21: from dry-validation-0.12.1/lib/dry/validation/executor.rb:85:in `block in call'
  20: from dry-validation-0.12.1/lib/dry/validation/executor.rb:37:in `call'
  19: from dry-validation-0.12.1/lib/dry/validation/executor.rb:37:in `each_with_object'
  18: from dry-validation-0.12.1/lib/dry/validation/executor.rb:37:in `each'
  17: from dry-validation-0.12.1/lib/dry/validation/executor.rb:38:in `block in call'
  16: from dry-logic-0.4.2/lib/dry/logic/operations/implication.rb:20:in `call'
  15: from dry-logic-0.4.2/lib/dry/logic/operations/and.rb:17:in `call'
  14: from dry-logic-0.4.2/lib/dry/logic/operations/key.rb:39:in `call'
  13: from dry-validation-0.12.1/lib/dry/validation/schema.rb:72:in `call'
  12: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `call'
  11: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `reduce'
  10: from dry-validation-0.12.1/lib/dry/validation/executor.rb:83:in `each'
   9: from dry-validation-0.12.1/lib/dry/validation/executor.rb:85:in `block in call'
   8: from dry-validation-0.12.1/lib/dry/validation/executor.rb:46:in `call'
   7: from dry-validation-0.12.1/lib/dry/validation/executor.rb:46:in `each_with_object'
   6: from dry-validation-0.12.1/lib/dry/validation/executor.rb:46:in `each'
   5: from dry-validation-0.12.1/lib/dry/validation/executor.rb:47:in `block in call'
   4: from dry-validation-0.12.1/lib/dry/validation/executor.rb:47:in `each'
   3: from dry-validation-0.12.1/lib/dry/validation/executor.rb:48:in `block (2 levels) in call'
   2: from dry-validation-0.12.1/lib/dry/validation/schema_compiler.rb:14:in `call'
   1: from dry-logic-0.4.2/lib/dry/logic/operations/check.rb:33:in `call'
dry-logic-0.4.2/lib/dry/logic/rule.rb:58:in `curry': wrong number of arguments (0 for -1) (ArgumentError)
```

**Comment by solnic** [comment]
This functionality was removed in dry-schema and in dry-validation 1.0.0 you’ll be able to use the new rule system to achieve the same thing.
