### ISSUE TITLE
Rules raises ArgumentError on failure with hash message

### ISSUE THREAD

**Issue by dsennerlov** [dry-rb/dry-validation#584]
**Describe the bug**

Calling `key.failure` with hash message in `rule` raises `ArgumentError: +message+ must be either a Symbol, String or Hash (nil given)`

**To Reproduce**

```ruby
class SimpleForm < Dry::Validation::Contract
  json do
    required(:name).filled(:string)
  end

  rule(:name) do
    key.failure(key: 'value', other_key: 'other_value')
  end
end
SimpleForm.new.call(name: 'Batman')
# --> ArgumentError: +message+ must be either a Symbol, String or Hash (nil given)
```
**Expected behavior**

No exception raised, and input hash should be used as error message

**Your environment**

- Affects my production application: No
- Ruby version: 2.5.1
- OS: Ubuntu

#### Stack trace
```ruby
ArgumentError: +message+ must be either a Symbol, String or Hash (nil given)

    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/messages/resolver.rb:40:in `call'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/messages/resolver.rb:38:in `call'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:101:in `block (3 levels) in call'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:100:in `each'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:100:in `block (2 levels) in call'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:95:in `each'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:95:in `block in call'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/result.rb:25:in `new'
    /home/vagrant/.bundler/ruby/2.5.0/gems/dry-validation-1.3.1/lib/dry/validation/contract.rb:94:in `call'
```
#### Gemfile.lock
```ruby
    dry-configurable (0.8.3)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.4, >= 0.4.7)
    dry-container (0.7.2)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.4.9)
      concurrent-ruby (~> 1.0)
    dry-equalizer (0.2.2)
    dry-inflector (0.1.2)
    dry-initializer (3.0.1)
    dry-logic (1.0.3)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.2)
      dry-equalizer (~> 0.2)
    dry-schema (1.3.3)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.8, >= 0.8.3)
      dry-core (~> 0.4)
      dry-equalizer (~> 0.2)
      dry-initializer (~> 3.0)
      dry-logic (~> 1.0)
      dry-types (~> 1.0)
    dry-struct (1.0.0)
      dry-core (~> 0.4, >= 0.4.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 1.0)
      ice_nine (~> 0.11)
    dry-types (1.1.1)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer (~> 0.2, >= 0.2.2)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 1.0, >= 1.0.2)
    dry-validation (1.3.1)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.7, >= 0.7.1)
      dry-core (~> 0.4)
      dry-equalizer (~> 0.2)
      dry-initializer (~> 3.0)
      dry-schema (~> 1.0, >= 1.3.1)
```

**Comment by MatElGran** [comment]
Hi @dsennerlov 

The code expects at least a `text` key in the provided hash, and the rest of the hash will be available as the meta attribute of the error message ie this: 

```ruby
class SimpleForm < Dry::Validation::Contract
  json do
    required(:name).filled(:string)
  end

  rule(:name) do
    key.failure(text: 'whatever', key: 'value', other_key: 'other_value')
  end
end
```

will work like this:

```ruby
result = SimpleForm.new.call({name: 'Batman'})
# => #<Dry::Validation::Result{:name=>"Batman"} errors={:name=>[{:text=>"whatever", :key=>"value", :other_key=>"other_value"}]}>

result.errors
# => #<Dry::Validation::MessageSet messages=[#<Dry::Validation::Message text="whatever" path=[:name] meta={:key=>"value", :other_key=>"other_value"}>] options={}>

result.errors.messages
# => [#<Dry::Validation::Message text="whatever" path=[:name] meta={:key=>"value", :other_key=>"other_value"}>]

result.errors.messages.map(&:meta)
# => [{:key=>"value", :other_key=>"other_value"}]
```

Maybe we could add a more useful error message in this particular case, and modify the documentation so that this point is a bit more explicit ? @solnic WDYT ?

**Comment by solnic** [comment]
> Maybe we could add a more useful error message in this particular case, and modify the documentation so that this point is a bit more explicit ? @solnic WDYT ?

Yes that's the way to make this better. This method doesn't work with arbitrary hashes after all.

**Comment by skryukov** [comment]
@solnic this can be closed?
