### ISSUE TITLE
I18n Namespaced messages and Sum(String, Symbol) types crash with NameError

### ISSUE THREAD

**Issue by fnordfish** [dry-rb/dry-validation#692]
## Describe the bug

I'm not 100% sure whether this is a dry-validation or dry-schema bug. I've encountered it using dry-validation.

Using contract with:
- message backend `:i18n`
- a custom message namespace 
- a param using a dry-types Sum type of String and Symbol (see below)

Other Sum types - I've testes `String | Nil`, `String | String` - seem to work.

## To Reproduce

```ruby
require "pp"
require "i18n"
require "yaml"
require "dry-types"
require "dry-validation"

dry_schma_i18n = YAML.safe_load_file("/usr/local/bundle/gems/dry-schema-1.8.0/config/errors.yml", symbolize_names: true)
data = {
  dry_validation: dry_schma_i18n[:en][:dry_schema]
}
data[:dry_validation][:errors][:Users] = {
  rules: {
    name: { filled?: "Bitte ausfüllen."},
    lang: { format?: "Hä?!" }
  }
}
I18n.backend.store_translations(:de, data)
I18n.default_locale = :de

module Types
  include Dry.Types()

  LangT = Types::Symbol.constrained(format: /\A[a-z]{2}\z/i) | Types::String.constrained(format: /\A[a-z]{2}\z/i)
end

class MyContract < Dry::Validation::Contract
  config.messages.default_locale = :de
  config.messages.backend = :i18n
  config.messages.namespace = :Users

  params do
    required(:name).filled(:string)
    optional(:lang).value(Types::LangT)
  end
end

pp MyContract.new.call(name: "", lang: "de").errors.to_h
# => {:name=>["Bitte ausfüllen."]}

pp MyContract.new.call(name: "", lang: "").errors.to_h
# /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/messages/abstract.rb:72:in `translate': undefined local variable or method `t' for #<Dry::Schema::Messages::Namespaced config=#<Dry::Configurable::Config values={:default_locale=>:de, :load_paths=>#<Set: {#<Pathname:/usr/local/bundle/gems/dry-schema-1.8.0/config/errors.yml>, #<Pathname:/usr/local/bundle/gems/dry-validation-1.7.0/config/errors.yml>}>, :top_namespace=>"dry_validation", :root=>"dry_validation.errors", :lookup_options=>[:root, :predicate, :path, :val_type, :arg_type], :lookup_paths=>["%<root>s.rules.%<path>s.%<predicate>s.arg.%<arg_type>s", "%<root>s.rules.%<path>s.%<predicate>s", "%<root>s.%<predicate>s.%<message_type>s", "%<root>s.%<predicate>s.value.%<path>s", "%<root>s.%<predicate>s.value.%<val_type>s.arg.%<arg_type>s", "%<root>s.%<predicate>s.value.%<val_type>s", "%<root>s.%<predicate>s.arg.%<arg_type>s", "%<root>s.%<predicate>s"], :rule_lookup_paths=>["dry_validation.rules.%<name>s"], :arg_types=>{Range=>"range"}, :val_types=>{Range=>"range", String=>"string"}}>> (NameError)
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message_compiler.rb:126:in `block in or_translator'
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message/or/single_path.rb:41:in `dump'
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message/or/single_path.rb:53:in `to_h'
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message_set.rb:108:in `map'
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message_set.rb:108:in `messages_map'
#   from /usr/local/bundle/gems/dry-schema-1.8.0/lib/dry/schema/message_set.rb:60:in `to_h'
#   from /usr/local/bundle/gems/dry-validation-1.7.0/lib/dry/validation/message_set.rb:92:in `freeze'
#   from /usr/local/bundle/gems/dry-validation-1.7.0/lib/dry/validation/result.rb:192:in `freeze'
#   from /usr/local/bundle/gems/dry-validation-1.7.0/lib/dry/validation/result.rb:26:in `new'
#   from /usr/local/bundle/gems/dry-validation-1.7.0/lib/dry/validation/contract.rb:105:in `call'
#   from issue.rb:40:in `<main>'
```

## Expected behavior

Does not crash and use the namespace error message.

## My environment

- Affects my production application: **YES** (But I have a workaround: `Types.Interface(:casecmp).constrained(format: /\A[a-z]{2}\z/i)`)
- Ruby version: ruby 3.0.2p107
- OS: Docker Image `ruby:3.0.2-bullseye` aka `Linux be394d66612e 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 GNU/Linux`

**Comment by solnic** [comment]
This will be fixed in dry-validation 1.8.0 / dry-schema 1.9.1
