### ISSUE TITLE
Dry::Core::Container::KeyError: There is already an item registered with the key

### ISSUE THREAD

**Issue by dawidof** [dry-rb/dry-validation#738]
## Describe the bug

First time it works ok, then I make one two other requests and request with this contract and receiving 
```json
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<Dry::Core::Container::KeyError: There is already an item registered with the key \"zip_code\">",
  "traces": {
    "Application Trace": [
      {
        "exception_object_id": 82780,
        "id": 7,
        "trace": "app/contracts/macros/address.rb:5:in `<module:Address>'"
      },
      {
        "exception_object_id": 82780,
        "id": 8,
        "trace": "app/contracts/macros/address.rb:4:in `<module:Macros>'"
      },
      {
        "exception_object_id": 82780,
        "id": 9,
        "trace": "app/contracts/macros/address.rb:3:in `<main>'"
      },
      {
```

## To Reproduce

```ruby
# frozen_string_literal: true

# Path: app/contracts/macros/address.rb
module Macros
  module Address
    Dry::Validation.register_macro(:zip_code) do
      key.failure(:invalid_zip_code) unless /\A\d{2}-\d{3}\z/.match?(value.to_s)
    end
  end
end

```
```ruby
# frozen_string_literal: true

# Path: app/contracts/users/create_contract.rb
module Users
  class CreateContract < ApplicationContract
    config.messages.namespace = :users

    include Macros::Address

    params do
      required(:name).filled(:string)
      required(:city).filled(:string)
      required(:zip_code).filled(:string)
      required(:contract_city).filled(:string)
      required(:contract_zip_code).filled(:string)
    end

    rule(:zip_code).validate(:zip_code)
    rule(:contract_zip_code).validate(:zip_code)
  end
end
```

## My environment

- Affects my production application: not working on development
- Rails 8.0.1
- Ruby version: 3.3.6
- OS: MacOS

**Comment by dawidof** [comment]
Made some workaround 
```ruby
# frozen_string_literal: true

# Path: app/contracts/macros/address.rb
module Macros
  module Address
    unless Dry::Validation::Macros.container.key?('zip_code')
      Dry::Validation.register_macro(:zip_code) do
        key.failure(:invalid_zip_code) unless /\A\d{2}-\d{3}\z/.match?(value.to_s)
      end
    end
  end
end
```

**Comment by flash-gordon** [comment]
Your code reloader is doing it, it's a matter of setting it up correctly. Macros must be defined once. If you use Rails there's a directory for initializers where code like this goes.
