### ISSUE TITLE
Cannot validate nested array with just one key defined

### ISSUE THREAD

**Issue by blelump** [dry-rb/dry-validation#75]
Hi @solnic ,

while validating schema against nested array with just one key defined, e.g:
```
require 'bundler'
Bundler.require

schema = Dry::Validation.Form do
  key(:nested).each do
      key(:name).required
  end
end

p schema.({"nested" => [{ "name" => 'Jane', age: 21 }, { name: 'Joe', age: nil }]}).messages
```

it returns:

```
/media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:15:in `visit': undefined method `visit_n' for #<Dry::Types::Compiler:0x0000000284dd78 @registry=Dry::Types> (NoMethodError)
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:11:in `call'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:38:in `visit_form_array'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:23:in `visit_type'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:15:in `visit'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:53:in `visit_key'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:15:in `visit'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:58:in `block in merge_with'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:58:in `map'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:58:in `merge_with'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:48:in `visit_form_hash'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:23:in `visit_type'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:15:in `visit'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-types-0.6.0/lib/dry/types/compiler.rb:11:in `call'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation/input_processor_compiler.rb:16:in `call'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation/schema.rb:104:in `input_processor'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation/schema.rb:127:in `default_options'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation/schema.rb:45:in `new'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation.rb:36:in `Schema'
        from /media/slave/work/.rvm/gems/ruby-2.2.4@isa/gems/dry-validation-0.7.0/lib/dry/validation.rb:41:in `Form'
```

However, if there's more than one key given, it spins fine.

**Comment by solnic** [comment]
This is a similar bug to what we had with `hash? do .. end`. I'm gonna fix it soon and push a small bug fix release. Thanks for reporting.
