### ISSUE TITLE
Add support for validating Dry::Types::Struct

### ISSUE THREAD

**Issue by coop** [dry-rb/dry-validation#85]
At the moment the following raises an exception:

```ruby
require "rspec"
require "dry-types"
require "dry-validation"

module Types
  include Dry::Types.module
end

class Rate < Dry::Types::Value
  attribute :variable, Types::Strict::Decimal
end

RSpec.describe "validate other structs/values" do
  it "should work" do
    schema = Dry::Validation.Schema do
      key(:rate).required(Rate)
    end

    expect(schema.(rate: {variable: "0.06"})).be be_success
  end
end
```

```
$ rspec struct_spec.rb
F

Failures:

  1) validate other structs/values should work
     Failure/Error: key(:rate).required(Rate)

     NoMethodError:
       undefined method `to_ast' for Rate:Class
       Did you mean?  to_s
     # ./struct_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./struct_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 0.00063 seconds (files took 0.48085 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./struct_spec.rb:14 # validate other structs/values should work
```

**Comment by coop** [comment]
At the moment I believe this would work if you did:

``` ruby
Dry::Validation.Schema do
  key(:rate).schema do
    key(:variable).required(Types::Strict::Decimal)
  end
end
```

Ideally dry-v can infer the correct validation from `Rate.struct`.

**Comment by solnic** [comment]
Just for the clarity, this is more about inferring validation schema from a constrained struct definition. We're still going to validate data, not structs.

**Comment by coop** [comment]
Yep - the idea is that you can pull the required validations from the struct definition.
