### ISSUE TITLE
Form: can't define array predicate with block syntax

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#94]
Here's how to reproduce the error:

```ruby
require 'dry-validation'

form = Dry::Validation.Form do
  key(:foo) { array? { each { int? } } }
end
NoMethodError: undefined method `each_with_object' for #<Dry::Types::Constructor:0x007fab2229d158>
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/constructor.rb:69:in `method_missing'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/hash.rb:7:in `schema'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/hash.rb:23:in `symbolized'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/decorator.rb:35:in `method_missing'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:66:in `merge_with'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:54:in `visit_form_hash'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:28:in `visit_type'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:15:in `visit'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:11:in `call'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:43:in `visit_form_array'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:28:in `visit_type'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:15:in `visit'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:62:in `visit_key'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:15:in `visit'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:67:in `block in merge_with'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-types-0.7.0/lib/dry/types/compiler.rb:67:in `map'
... 8 levels...
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-validation-0.7.3/lib/dry/validation/schema.rb:45:in `new'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-validation-0.7.3/lib/dry/validation.rb:36:in `Schema'
	from /Users/luca/.gem/ruby/2.3.0/gems/dry-validation-0.7.3/lib/dry/validation.rb:41:in `Form'
	from (irb):7
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/cli/console.rb:14:in `run'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:319:in `console'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /Users/luca/.gem/ruby/2.3.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
	from /Users/luca/.gem/ruby/2.3.0/bin/bundle:23:in `load'
```

It works fine, with the macro syntax:

```ruby
require 'dry-validation'

form = Dry::Validation.Form do
  key(:foo).each(:int?)
end
```

**Comment by AMHOL** [comment]
@jodosha this appears to work on the master branch, could you test from there and let me know if it's still an issue, thanks

**Comment by jodosha** [comment]
@AMHOL Yes, it works! Thanks for letting me know.
